VERSION="1.0.0"

[[PRINCIPALS]]
name="Tokens Issuer"

[[CURRENCIES]]
code="Garbi314k"
issuer="GAFMNPNSJUC6OQJHRZ26YBLJVSBKWLMSXRJ35NHSJBUBCZYTXHSD7P3B"
name="Garbi 314k"
desc="Garbi 314k Community Token"
image="https://raw.githubusercontent.com/pinetws/pinetws.github.io/main/garbi314k.jpg"
